config:
  main_folder: /mnt/c/Users/sepeh/OneDrive/Documents/Git/GraphRag_Developer_Challenge3/.noderag
  language: English
  chunk_size: 700
  chunk_overlap: 50
  embedding_batch_size: 16
  dim: 1024
  docu_type: mixed
  similarity_weight: 1.0
  accuracy_weight: 10.0
  Hcluster_size: 39
  cross_node: 10
  Enode: 10
  Rnode: 10
  Hnode: 10
  HNSW_results: 10
  m: 5
  ef: 200
  space: cosine
  unbalance_adjust: false
  max_workers: 4
model_config:
  service_provider: openai
  model_name: gpt-4o-mini
  temperature: 0.0
  max_tokens: 10000
  rate_limit: 50
embedding_config:
  service_provider: hf_embedding
  model_name: BAAI/bge-m3
  batch_size: 16
  embedding_model_name: OPENAI_EMBED_MODEL
  rate_limit: 50
